app = 'ebarrio-web-backend-6nymsa'
primary_region = 'sin'

[env]
  PORT="5000"
  DATABASE_URL="mongodb+srv://knicole:admin1234@cluster0.l40pk.mongodb.net/eBarrio?retryWrites=true&w=majority&appName=Cluster0"
  ACCESS_SECRET="myaccesssecret"
  REFRESH_SECRET="myrefreshsecret"
  REDIS_URL = "rediss://default:8371acac08424457a591b90d01c5a45c@gusc1-trusting-akita-31569.upstash.io:31569"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

